name: CICD

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cv:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
#      - name: Terraform Format Check
#        id: fmt
#        run: terraform fmt -check
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Apply
        run: >
          terraform apply
          -var 'docker_image="${{ secrets.DOCKER_HUB_USERNAME }}/cv:${{ github.sha }}"'
          -var 'aws_region="eu-north-1"'
          -var 'aws_cert_bucket="${{ secrets.AWS_CERT_BUCKET }}"'
          -var aws_cert_bucket_arn="${{ secrets.AWS_CERT_BUCKET_ARN }}"
          -auto-approve
